apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applicationset-manager
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: 'https://github.com/lhc/k8s1.git'
        revision: 'main'
        directories:
          - path: 'applicationsets'
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/lhc/k8s1.git'
        targetRevision: 'main'
        path: '{{path}}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true

